### ISSUE TITLE
Overwriting zarr seems impossible

### ISSUE THREAD

**Issue by StefanBrand** [ungarj/mapchete_xarray#9]
I'm using output storage `zarr`, but when I try `mhub execute ... --overwrite`, I get this traceback:

```log
Traceback (most recent call last):
  File \"/usr/local/lib/python3.6/site-packages/celery/app/trace.py\", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File \"/usr/local/lib/python3.6/site-packages/celery/app/trace.py\", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File \"/usr/local/src/mapchete_hub/mapchete_hub/commands/execute.py\", line 48, in run
    for i, _ in enumerate(executor):
  File \"/usr/local/src/mapchete_hub/mapchete_hub/commands/_execute.py\", line 79, in mapchete_execute
    max_chunksize=max_chunksize
  File \"/usr/local/lib/python3.6/site-packages/mapchete/_core.py\", line 264, in batch_processor
    skip_output_check=skip_output_check
  File \"/usr/local/lib/python3.6/site-packages/mapchete/_processing.py\", line 501, in _run_area
    skip_output_check=skip_output_check
  File \"/usr/local/lib/python3.6/site-packages/mapchete/_processing.py\", line 601, in _run_multi
    process_info = task.result()
  File \"/usr/local/lib/python3.6/site-packages/mapchete/_processing.py\", line 427, in result
    raise self._exception
  File \"/usr/local/lib/python3.6/site-packages/mapchete/_processing.py\", line 419, in __init__
    self._result, self._exception = func(*fargs, **fkwargs), None
  File \"/usr/local/lib/python3.6/site-packages/mapchete/_processing.py\", line 702, in _execute_and_write
    output_writer=output_writer
  File \"/usr/local/lib/python3.6/site-packages/mapchete/_processing.py\", line 683, in _write
    output_writer.write(process_tile=process_info.tile, data=output_data)
  File \"/usr/local/lib/python3.6/site-packages/mapchete_xarray/_xarray.py\", line 181, in write
    encoding={\"data\": self._get_encoding()}
  File \"/usr/local/lib/python3.6/site-packages/xarray/core/dataset.py\", line 1658, in to_zarr
    append_dim=append_dim,
  File \"/usr/local/lib/python3.6/site-packages/xarray/backends/api.py\", line 1348, in to_zarr
    consolidate_on_close=consolidated,
  File \"/usr/local/lib/python3.6/site-packages/xarray/backends/zarr.py\", line 287, in open_group
    zarr_group = zarr.open_group(store, **open_kwargs)
  File \"/usr/local/lib/python3.6/site-packages/zarr/hierarchy.py\", line 1161, in open_group
    err_contains_group(path)
  File \"/usr/local/lib/python3.6/site-packages/zarr/errors.py\", line 13, in err_contains_group
    raise ValueError('path %r contains a group' % path)
ValueError: path '' contains a group

```

The exception `path '' contains a group` is familiar to me from prior zarr experiments.

PS.: This is the `mapchete` file:

```yaml
process: xarray_export.py
input:
  aoi: s3://eox-masterdatacube/mapchete_cubes/mab.geojson
  satellite_cube:
    format: S2AWS
    start_time: 2019-09-01
    end_time: 2019-09-30
    level: L2A
    with_cloudmasks: true
    metadata_concurrency: true
    max_products: 3700
    remote_timeout: 60
    cache:
      path: /mnt/data/cache
      intersection_percent: 0.5
      bands: [2, 3, 4, 5, 6, 7, 8, 9, 11, 12]
output:
  format: xarray
  path: s3://eox-masterdatacube/mapchete_cubes/MAB_p/
  dtype: uint16
  storage: zarr
pyramid:
  grid:
    shape: [115, 9]
    bounds: [186210.0, -9800.0, 923490.0, 9411000.0]
    is_global: False
    epsg: 32633
  metatiling: 2
zoom_levels: 5
```
